project_name: telecom-tower-simulator

builds:
  - binary: telecom-tower-simulator
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md

brew:
  github:
    owner: telecom-tower
    name: homebrew-tap

  commit_author:
    name: goreleaserbot
    email: goreleaser@telecomtower.xyz

  folder: Formula
  homepage: "https://github.com/telecom-tower"
