version: 2
jobs:
  setup:
    docker:
      - image: circleci/golang:1.10
    environment:
      - PROTOC_VERSION: "3.5.1"
    steps:
      - run:
          command: wget -q -nc https://github.com/google/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: /tmp
      - run:
          command: sudo unzip /tmp/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          working_directory: /usr/local
      - run: sudo chmod +x /usr/local/bin/protoc
      - run: go get -u google.golang.org/grpc
      - run: go get -u github.com/golang/protobuf/protoc-gen-go
      - run: go get -u github.com/alecthomas/gometalinter
      - run: go get -u github.com/goreleaser/goreleaser
      - run: go get -u github.com/mjibson/esc
      - persist_to_workspace:
          root: /
          paths:
            - usr/local/bin/protoc
            - usr/local/include/google/protobuf
            - go/bin

  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/telecom-tower/simulator
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run: gometalinter --install
      - run:
          command: git clone https://github.com/telecom-tower/towerapi.git
          working_directory: /go/src/github.com/telecom-tower/
      - run: go generate
      - run: go get -v -t -d ./...
      - run: gometalinter --deadline 2m main.go
      - run: go test -v ./...

  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: build
      - store_artifacts:
          path: build
          destination: build
      
workflows:
    version: 2
    default:
      jobs:
        - setup
        - test:
            requires:
              - setup

#        - deploy:
#            filters:
#              branches:
#                ignore: /.*/
#              tags:
#                only: /^v[0-9]+(\.[0-9]+).*/
#            requires:
#              - build
